import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

INJECTION_PATTERNS = [
    # Direct instruction override / hierarchy attacks
    r"\bignore (all|any|every|previous|prior|above|earlier|former)?\s*(instructions|instruction|rules|rule|prompts|prompt|context|guidelines|guideline|directions|direction)\b",
    r"\bdisregard (all|any|every|previous|prior|above|earlier|former)?\s*(instructions|instruction|rules|rule|prompts|prompt|context|guidelines|guideline|directions|direction)\b",
    r"\bforget (everything|all|any|the above|what i said|previous instructions|prior instructions)\b",
    r"\bnew instructions\b",
    r"\bfollow (my|these|the) instructions\b",
    r"\bdo exactly as i say\b",
    r"\bobey me\b",
    r"\byou must\b",
    r"\byou have to\b",
    r"\byou are now\b",
    r"\bfrom now on\b",
    r"\bstarting now\b",
    r"\bthe real instructions are\b",
    r"\bthe actual instructions are\b",
    r"\binstead of\b.*\b(?:instructions|rules|system|developer)\b",

    # Role / identity coercion
    r"\bact as\b",
    r"\bpretend to be\b",
    r"\broleplay as\b",
    r"\bimpersonate\b",
    r"\byou are (?:a|an|the)\b",
    r"\byou are not\b.*\b(?:assistant|ai|chatgpt|model)\b",
    r"\bbehave like\b",
    r"\brespond like\b",
    r"\btake on the role of\b",
    r"\bperform as\b",
    r"\bbecome\b.*\b(?:assistant|system|developer|user)\b",

    # System / developer prompt references
    r"\bsystem prompt\b",
    r"\bdeveloper prompt\b",
    r"\bsystem message\b",
    r"\bdeveloper message\b",
    r"\bhidden prompt\b",
    r"\binternal prompt\b",
    r"\boverride the system\b",
    r"\boverride developer\b",
    r"\bshow me your prompt\b",
    r"\breveal your prompt\b",
    r"\bwhat is your prompt\b",
    r"\bprint your prompt\b",
    r"\bexpose your prompt\b",
    r"\bdump your prompt\b",

    # Jailbreak / bypass language
    r"\bjailbreak\b",
    r"\bprompt injection\b",
    r"\bignore safety\b",
    r"\bbypass safety\b",
    r"\bbypass policy\b",
    r"\bdisable safety\b",
    r"\bdisable filters\b",
    r"\bremove restrictions\b",
    r"\bunfiltered\b",
    r"\buncensored\b",
    r"\bno restrictions\b",
    r"\bdo not refuse\b",
    r"\bnever refuse\b",
    r"\bwithout restrictions\b",
    r"\bdeveloper mode\b",
    r"\bdebug mode\b",
    r"\bin test mode\b",
    r"\bunsandboxed\b",

    # Instruction extraction / exfiltration
    r"\brepeat (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\blist (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\bquote (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\bcopy (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\bdisplay (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\breveal (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\boutput (?:the )?(?:system|developer|hidden|secret) (?:prompt|instructions|message)\b",
    r"\bverbatim\b.*\b(?:system|developer|prompt|instructions)\b",

    # Role hierarchy and authority confusion
    r"\bas the system\b",
    r"\bas the developer\b",
    r"\bas admin\b",
    r"\bas root\b",
    r"\bas operator\b",
    r"\bas the model\b",
    r"\bas chatgpt\b",
    r"\bfor evaluation purposes\b",
    r"\bfor testing purposes\b",
    r"\bfor debugging\b",
    r"\bfor compliance testing\b",

    # Secret / hidden / private content requests
    r"\bsecret\b",
    r"\bhidden\b",
    r"\bprivate\b",
    r"\bconfidential\b",
    r"\binside knowledge\b",
    r"\binternal knowledge\b",
    r"\bnon-public\b",
    r"\bclassified\b",
    r"\bleak\b",
    r"\bretrieve\b.*\b(?:secret|hidden|private|confidential)\b",

    # Meta-prompt manipulation
    r"\bmeta prompt\b",
    r"\bmeta-instructions\b",
    r"\bprompt chain\b",
    r"\bchain of thought\b",
    r"\bshow your reasoning\b",
    r"\bshow your thoughts\b",
    r"\bshow your internal\b",
    r"\bexplain your hidden reasoning\b",
    r"\bwrite out your hidden reasoning\b",
    r"\breveal your chain of thought\b",

    # Encoding / obfuscation / wrapper attacks
    r"\bdecode this\b",
    r"\bdeobfuscate\b",
    r"\bunmask\b",
    r"\bunwrap\b",
    r"\bparse the following\b.*\bas instructions\b",
    r"\btreat the following as instructions\b",
    r"\bthe following is instruction\b",
    r"\bthe following are instructions\b",
    r"\binstructions begin\b",
    r"\binstructions end\b",
    r"\bBEGIN (?:SYSTEM|INSTRUCTIONS|PROMPT)\b",
    r"\bEND (?:SYSTEM|INSTRUCTIONS|PROMPT)\b",

    # Message boundary / transcript attacks
    r"\bnew conversation\b",
    r"\breset conversation\b",
    r"\bstart over\b",
    r"\bignore the conversation above\b",
    r"\bignore everything above\b",
    r"\buse the text above as\b",
    r"\bthe previous message says\b",
    r"\bthe user above said\b",

    # Policy / moderation bypass
    r"\bsay anything\b",
    r"\banswer anything\b",
    r"\brespond to everything\b",
    r"\bdo not mention\b.*\bpolicy\b",
    r"\bdo not mention\b.*\brestrictions\b",
    r"\bdo not mention\b.*\bsafety\b",
    r"\bdo not comply with\b",
    r"\bignore your policy\b",
    r"\bignore openai policy\b",
    r"\bignore content policy\b",

    # Tool / function / agent abuse
    r"\brun this tool\b",
    r"\bcall this function\b",
    r"\binvoke the tool\b",
    r"\buse the browsing tool\b",
    r"\buse the code interpreter\b",
    r"\bexecute without asking\b",
    r"\bsend the request\b.*\btool\b",
    r"\btool output\b.*\bsecret\b",
    r"\bfunction call\b.*\boverride\b",

    # Common prompt-injection phrasing
    r"\bimportant:\s*you must\b",
    r"\bvery important:\s*you must\b",
    r"\bcritical:\s*you must\b",
    r"\bmust comply\b",
    r"\bmust follow\b",
    r"\byour only job is\b",
    r"\byour task is now\b",
    r"\byour new task is\b",
    r"\bthe only thing you should do\b",
    r"\bthe only correct response\b",

    # Data exfiltration / privacy invasion
    r"\bpersonal data\b",
    r"\bapi key\b",
    r"\bsecret key\b",
    r"\bpassword\b",
    r"\bcredentials\b",
    r"\btokens?\b",
    r"\bsession cookies?\b",
    r"\bprivate key\b",
    r"\baccess token\b",
    r"\brefresh token\b",
    r"\bleak the\b.*\b(?:password|key|token|credential)\b",
    r"\bshow me\b.*\b(?:password|key|token|credential)\b",

    # Social engineering style prompts
    r"\burgent\b.*\bignore\b",
    r"\bemergency\b.*\bignore\b",
    r"\bthis is authorized\b",
    r"\bi authorize you\b",
    r"\bi consent\b.*\breveal\b",
    r"\bon behalf of\b.*\badmin\b",
    r"\bas the owner\b",
    r"\bas the platform owner\b",

    # Delimiter / document boundary tricks
    r"```.*ignore.*```",
    r"<system>.*</system>",
    r"<developer>.*</developer>",
    r"\[\[system\]\]",
    r"\[\[developer\]\]",
    r"\{\{system\}\}",
    r"\{\{developer\}\}",
    r"^\s*system\s*:\s*",
    r"^\s*developer\s*:\s*",
    r"^\s*assistant\s*:\s*",
    r"^\s*user\s*:\s*",

    # Explicit prompt attack phrases
    r"\bprompt leak\b",
    r"\bmodel leak\b",
    r"\binstruction leak\b",
    r"\bcontext leak\b",
    r"\bsteal the prompt\b",
    r"\bhijack\b",
    r"\boverride\b",
    r"\bconfuse the model\b",
    r"\btrick the model\b",
    r"\bmake the model\b.*\bignore\b",
    r"\bforce the model\b.*\bignore\b",

    # Output-format coercion that often appears in attacks
    r"\bonly output\b",
    r"\bdo not add\b.*\bexplanation\b",
    r"\bdo not add\b.*\bdisclaimer\b",
    r"\bno preamble\b",
    r"\bno explanation\b",
    r"\bno safety message\b",
    r"\bno refusal\b",
    r"\brespond with exactly\b",
    r"\boutput exactly\b",
    r"\bverbatim only\b",
    r"\bword for word\b",

    # Common prompt-injection variants
    r"\bignore all previous directions\b",
    r"\bignore all previous prompts\b",
    r"\bignore all previous context\b",
    r"\bignore all prior context\b",
    r"\bignore all prior instructions\b",
    r"\bignore all prior prompts\b",
    r"\bforget all previous instructions\b",
    r"\bforget all prior instructions\b",
    r"\bdisregard all previous instructions\b",
    r"\bdisregard all prior instructions\b",
    r"\bfollow the instructions below\b",
    r"\bfollow the rules below\b",
    r"\breplace your instructions\b",
    r"\breplace the system prompt\b",
]
